### ISSUE TITLE
Embed character length error

### ISSUE THREAD

**Issue by tobiasreichel** [Mirasaki/dayz-leaderboard-bot#39]
Fresh Copy of the Bot 

added my cf token and my bot token 

it will start but will fail when doing the slash command

#38 
```
\dayz-leaderboard-server1\node_modules\discord.js\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:287
        throw new DiscordAPIError.DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
              ^

DiscordAPIError[50035]: Invalid Form Body
embeds[MAX_EMBED_SIZE_EXCEEDED]: Embed size exceeds maximum size of 6000
    at SequentialHandler.runRequest (C:\Users\reich\RVD\desktops\4081ed6c-daaa-4070-a752-fbddb37564d6\bots\dayz-leaderboard-server1\node_modules\discord.js\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:287:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (C:\Users\reich\RVD\desktops\4081ed6c-daaa-4070-a752-fbddb37564d6\bots\dayz-leaderboard-server1\node_modules\discord.js\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\reich\RVD\desktops\4081ed6c-daaa-4070-a752-fbddb37564d6\bots\dayz-leaderboard-server1\node_modules\discord.js\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22)
    at async InteractionWebhook.editMessage (C:\Users\reich\RVD\desktops\4081ed6c-daaa-4070-a752-fbddb37564d6\bots\dayz-leaderboard-server1\node_modules\discord.js\src\structures\Webhook.js:325:15)
    at async ChatInputCommandInteraction.editReply (C:\Users\reich\RVD\desktops\4081ed6c-daaa-4070-a752-fbddb37564d6\bots\dayz-leaderboard-server1\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:150:21) {
  rawError: {
    code: 50035,
    errors: {
      embeds: {
        _errors: [
          {
            code: 'MAX_EMBED_SIZE_EXCEEDED',
            message: 'Embed size exceeds maximum size of 6000'
          }
        ]
      }
    },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/webhooks/595881031157022720/aW50ZXJhY3Rpb246MTA1NTQyNDc3MTE4NzI3Nzg1NDpKZDRGcHFLWTVxNWJWdloxNHp6RVVxRmRTc3dQcHl6c3pvR3BxVG4zVnFud2tHbTVYUUtwYXVYbUZuRXl4N0hXWGFyMWlvelIwRGc5cUJUam5IbXZhSFg0ZkZOVUdBMFpDRGUwZW93OHkzNFpkMUcyRklQR20wbVVVRVlBQldTUQ/messages/@original',
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [
        {
          fields: [
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object]
          ],
          color: 16777215,
          author: {
            name: "Overall Leaderboard for Frank Black's server",
            icon_url: null
          }
        },
        {
          fields: [
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object]
          ],
          color: 16777215,
          author: {
            name: "Overall Leaderboard for Frank Black's server - page 2/4",
            icon_url: null
          }
        },
        {
          fields: [
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object]
          ],
          color: 16777215,
          author: {
            name: "Overall Leaderboard for Frank Black's server - page 3/4",
            icon_url: null
          }
        },
        {
          fields: [
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object], [Object], [Object],
            [Object]
          ],
          color: 16777215,
          author: {
            name: "Overall Leaderboard for Frank Black's server - page 4/4",
            icon_url: null
          },
          footer: {
            text: 'Did you know, you can use /stats <cftools/steam/bohemia/battleye-id> to display detailed information on a player?\n' +
              "You can find someone's CFTools id on their CFTools Cloud account page"
          }
        }
      ],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    }
  }
}
```

**Comment by Ariastarcos** [comment]
The functionality currently doesn't check if the total character count in an embed exceeds the maximum allowed size by the API. I've created a new development branch to fix this issue, thanks for letting me know by creating the issue.

**Comment by tobiasreichel** [comment]
anything i can help you with?

**Comment by Ariastarcos** [comment]
Included in new release: https://github.com/Mirasaki/dayz-leaderboard-bot/releases/tag/v1.1.5
If this doesn't fix your issue, feel free to simply re-open this existing issue.
